name: Build and Test
on:
  - push
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
      - uses: actions/checkout@v2
        
      - name: Setup .NET Core SDK 2.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '2.0'

      - name: Build
        run: dotnet build
